name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout snow_wiki repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pySNOW package from GitHub
        run: pip install git+https://github.com/your-username/pySNOW.git

      - name: Install dependencies for snow_wiki
        run: pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Build and deploy MkDocs site
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdocs build --clean
          mkdocs gh-deploy --force
